# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [nhrzxxw9dn-web]
custom:
  - "https://crawlertoll.com/sponsor"
  - "https://charthouse.io/contact"
